version: '3.8'

# Define services
services:

  # Database Service (MariaDB)
  database:
    image: mariadb:latest
    container_name: kppro-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: kppro_dovolena
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpasswd
      MYSQL_ROOT_PASSWORD: rootpasswd
    networks:
      - main-network
    volumes:
      - ./maria:/docker-entrypoint-initdb.d


  openjdk:
    container_name: kppro-jdk
    build: .
    depends_on:
      - database
    ports:
      - "8080:8080"
    restart: always
    networks:
      - main-network

networks:
  main-network:
    external: false
